// Fixture data for the local UI-check harness (mock Supabase). Not used in production.
//
// One entry per table/view the (app) pages read. Rows are supersets of every
// select shape a page uses (nested join objects are pre-embedded), and the
// arrays are pre-sorted to match each page's primary ordering because the mock
// ignores filters/order. IDs are consistent across tables. A few deliberately
// long strings (strain 2's name, batch 2's notes, customer 4 / vendor 2 names)
// stress layout overflow in screenshots.

const strainsGT = { id: 1, name: "Golden Teacher", mushroom_type: "psychedelic" };
const strainsSAPE = { id: 2, name: "Stargazer × Albino Penis Envy Isolate F4", mushroom_type: "psychedelic" };
const strainsJMF = { id: 3, name: "Jedi Mind Fuck", mushroom_type: "psychedelic" };
const strainsLM = { id: 4, name: "Lion's Mane", mushroom_type: "functional" };
const strainsBO = { id: 5, name: "Blue Oyster", mushroom_type: "gourmet" };
const strainsTW = { id: 6, name: "Tidal Wave", mushroom_type: "psychedelic" };

const roomA = { id: 1, name: "Fruiting Tent A" };
const roomB = { id: 2, name: "Colonization Rack" };
const roomC = { id: 3, name: "Lab Closet" };

export default {
  // ── Genetics ────────────────────────────────────────────────────────────
  strains: [
    {
      id: 1,
      name: "Golden Teacher",
      species: "Psilocybe cubensis",
      strain_code: "GT",
      mushroom_type: "psychedelic",
      vendor: "Sporeworks",
      genetics: "Classic GT line, F4 from multispore",
      potency: "moderate",
      ease_rating: 9,
      typical_be: 95,
      typical_flushes: 3,
      target_temp_c: 22,
      target_humidity: 92,
      target_co2_ppm: 800,
      syringes_on_hand: 4,
      library_status: "in_library",
      grow_again: true,
      active: true,
      notes: "House workhorse. Very forgiving of temp swings; canopy fruits evenly across the tub.",
      generation: 4,
      priority: 5,
      potency_tier: "Standard",
      alkaloid_total_pct: 0.86,
      alkaloid_total_low_pct: 0.61,
      alkaloid_total_high_pct: 1.12,
      psilocin_psilocybin_ratio: 0.14,
      spectrum_hue: 265,
      evidence_grade: "established",
      experience_summary:
        "Warm, teacherly classic — introspective without being heavy. The community's benchmark for a balanced first cultivar.",
      experience_tags: ["balanced", "introspective", "beginner-friendly"],
      onset_min: 30,
      peak_hr: 2,
      duration_hr: 5,
      profile_source: "Oakland Hyphae 2024 dataset",
      created_at: "2026-01-12T18:00:00Z",
    },
    {
      id: 2,
      name: "Stargazer × Albino Penis Envy Isolate F4", // ~40-char stress name
      species: "Psilocybe cubensis",
      strain_code: "SAPE-F4",
      mushroom_type: "psychedelic",
      vendor: "Pacific Northwest Mycological Supply & Genetics Preservation Co-op",
      genetics: "Stargazer × APE cross, agar isolate, F4",
      potency: "very high",
      ease_rating: 5,
      typical_be: 62,
      typical_flushes: 2,
      target_temp_c: 21,
      target_humidity: 94,
      target_co2_ppm: 700,
      syringes_on_hand: 2,
      library_status: "in_library",
      grow_again: true,
      active: true,
      notes:
        "Slow colonizer — expect 21+ days on grain. Dense blue-bruising fruits, small caps. Isolate held on two slants in the lab closet; do not push past F5 without re-isolating from a clean sector.",
      generation: 4,
      priority: 4,
      potency_tier: "Very high",
      alkaloid_total_pct: 1.82,
      alkaloid_total_low_pct: 1.4,
      alkaloid_total_high_pct: 2.3,
      psilocin_psilocybin_ratio: 0.22,
      spectrum_hue: 305,
      evidence_grade: "mixed",
      experience_summary:
        "Heavy, slow-building and long. Community reports skew visual and physical; dose conservatively versus GT.",
      experience_tags: ["intense", "visual", "long-duration"],
      onset_min: 45,
      peak_hr: 3,
      duration_hr: 7,
      profile_source: "Vendor assay + community reports",
      created_at: "2026-02-03T18:00:00Z",
    },
    {
      id: 3,
      name: "Jedi Mind Fuck",
      species: "Psilocybe cubensis",
      strain_code: "JMF",
      mushroom_type: "psychedelic",
      vendor: "Inoculate the World",
      genetics: "JMF multispore, F2",
      potency: "high",
      ease_rating: 7,
      typical_be: 78,
      typical_flushes: 3,
      target_temp_c: 22,
      target_humidity: 90,
      target_co2_ppm: 800,
      syringes_on_hand: 1,
      library_status: "in_library",
      grow_again: true,
      active: true,
      notes: "Big caps, fast pinset. Watch first flush for aborts if FAE lags.",
      generation: 2,
      priority: 3,
      potency_tier: "High",
      alkaloid_total_pct: 1.21,
      alkaloid_total_low_pct: 0.9,
      alkaloid_total_high_pct: 1.5,
      psilocin_psilocybin_ratio: 0.18,
      spectrum_hue: 285,
      evidence_grade: "anecdotal",
      experience_tags: ["euphoric", "creative"],
      experience_summary: "Bright and talkative up front, mellow landing.",
      onset_min: 25,
      peak_hr: 2,
      duration_hr: 5,
      profile_source: null,
      created_at: "2026-03-15T18:00:00Z",
    },
    {
      id: 4,
      name: "Lion's Mane",
      species: "Hericium erinaceus",
      strain_code: "LM-NS",
      mushroom_type: "functional",
      vendor: "North Spore",
      genetics: "Commercial production isolate",
      potency: null,
      ease_rating: 8,
      typical_be: 110,
      typical_flushes: 2,
      target_temp_c: 18,
      target_humidity: 95,
      target_co2_ppm: 600,
      syringes_on_hand: 0,
      library_status: "in_library",
      grow_again: true,
      active: true,
      notes: "Fruits best cold. Sells out at market every week.",
      generation: 1,
      priority: 5,
      potency_tier: null,
      alkaloid_total_pct: null,
      alkaloid_total_low_pct: null,
      alkaloid_total_high_pct: null,
      psilocin_psilocybin_ratio: null,
      spectrum_hue: null,
      evidence_grade: null,
      experience_summary: null,
      experience_tags: null,
      onset_min: null,
      peak_hr: null,
      duration_hr: null,
      profile_source: null,
      created_at: "2026-01-20T18:00:00Z",
    },
    {
      id: 5,
      name: "Blue Oyster",
      species: "Pleurotus ostreatus var. columbinus",
      strain_code: "BO-01",
      mushroom_type: "gourmet",
      vendor: "North Spore",
      genetics: "Cold-blue production strain",
      potency: null,
      ease_rating: 10,
      typical_be: 140,
      typical_flushes: 3,
      target_temp_c: 16,
      target_humidity: 92,
      target_co2_ppm: 700,
      syringes_on_hand: 0,
      library_status: "in_library",
      grow_again: false,
      active: false,
      notes: "Retired for summer — fruits poorly above 20°C in the garage.",
      generation: 1,
      priority: 2,
      potency_tier: null,
      alkaloid_total_pct: null,
      alkaloid_total_low_pct: null,
      alkaloid_total_high_pct: null,
      psilocin_psilocybin_ratio: null,
      spectrum_hue: null,
      evidence_grade: null,
      experience_summary: null,
      experience_tags: null,
      onset_min: null,
      peak_hr: null,
      duration_hr: null,
      profile_source: null,
      created_at: "2026-02-14T18:00:00Z",
    },
    {
      id: 6,
      name: "Tidal Wave",
      species: "Psilocybe cubensis",
      strain_code: "TW",
      mushroom_type: "psychedelic",
      vendor: null,
      genetics: "B+ × Penis Envy",
      potency: "very high",
      ease_rating: 6,
      typical_be: 70,
      typical_flushes: 2,
      target_temp_c: 22,
      target_humidity: 92,
      target_co2_ppm: 800,
      syringes_on_hand: 0,
      library_status: "unknown",
      grow_again: true,
      active: true,
      notes: "Cup-record genetics — want in the library. Crawler is hunting a source.",
      generation: 1,
      priority: 4,
      potency_tier: "Very high",
      alkaloid_total_pct: 2.26,
      alkaloid_total_low_pct: 1.2,
      alkaloid_total_high_pct: 3.82,
      psilocin_psilocybin_ratio: 0.35,
      spectrum_hue: 320,
      evidence_grade: "established",
      experience_summary: "Record-setting potency; fast and forceful.",
      experience_tags: ["intense", "fast-onset"],
      onset_min: 20,
      peak_hr: 2,
      duration_hr: 5,
      profile_source: "Oakland Hyphae Psilocybin Cup 2021",
      created_at: "2026-07-01T18:00:00Z",
    },
  ],

  // ── Rooms & environment ─────────────────────────────────────────────────
  rooms: [
    {
      id: 1,
      name: "Fruiting Tent A",
      room_type: "fruiting",
      capacity_blocks: 24,
      target_temp_c: 21,
      target_humidity: 90,
      target_co2_ppm: 800,
      target_fae_per_hr: 4,
      notes: "4x4 tent, AC Infinity controller",
    },
    {
      id: 2,
      name: "Colonization Rack",
      room_type: "incubation",
      capacity_blocks: 40,
      target_temp_c: 24,
      target_humidity: 70,
      target_co2_ppm: 5000,
      target_fae_per_hr: 1,
      notes: "Wire rack in the warm closet",
    },
    {
      id: 3,
      name: "Lab Closet",
      room_type: "lab",
      capacity_blocks: 12,
      target_temp_c: 20,
      target_humidity: 40,
      target_co2_ppm: 600,
      target_fae_per_hr: 2,
      notes: "Flow hood + still-air box",
    },
  ],

  v_environment_status: [
    {
      room_id: 1,
      room: "Fruiting Tent A",
      room_type: "fruiting",
      target_temp_c: 21,
      target_humidity: 90,
      target_co2_ppm: 800,
      target_fae_per_hr: 4,
      temp_c: 20.6,
      humidity: 87,
      co2_ppm: 1240,
      fae_per_hr: 3,
      in_spec: false,
    },
    {
      room_id: 2,
      room: "Colonization Rack",
      room_type: "incubation",
      target_temp_c: 24,
      target_humidity: 70,
      target_co2_ppm: 5000,
      target_fae_per_hr: 1,
      temp_c: 23.8,
      humidity: 68,
      co2_ppm: 3400,
      fae_per_hr: 1,
      in_spec: true,
    },
    {
      room_id: 3,
      room: "Lab Closet",
      room_type: "lab",
      target_temp_c: 20,
      target_humidity: 40,
      target_co2_ppm: 600,
      target_fae_per_hr: 2,
      temp_c: null,
      humidity: null,
      co2_ppm: null,
      fae_per_hr: null,
      in_spec: null,
    },
  ],

  // ── Batches (newest first; nested strains carries id+name+mushroom_type
  //    so every page's join shape is satisfied) ─────────────────────────────
  batches: [
    {
      id: 1,
      lot_code: "GT-2608-A",
      stage: "fruiting",
      strain_id: 1,
      room_id: 1,
      block_count: 4,
      substrate_weight_kg: 6.5,
      container_id: "TUB-07",
      container_type: "tub",
      tub_size: "66 qt",
      spawn_type: "rye grain",
      substrate_type: "CVG",
      bag_type: null,
      inoculated_on: "2026-07-02",
      colonized_on: "2026-07-16",
      fruiting_on: "2026-07-21",
      spent_on: null,
      contamination_flag: false,
      rating: 8,
      issues: null,
      notes: "Second flush pinning now. Canopy even, no side pins.",
      lineage_parent_id: null,
      created_at: "2026-07-02T15:00:00Z",
      strains: strainsGT,
      rooms: roomA,
    },
    {
      id: 6,
      lot_code: "GT-2608-B",
      stage: "colonization",
      strain_id: 1,
      room_id: 2,
      block_count: 4,
      substrate_weight_kg: 6.5,
      container_id: "TUB-09",
      container_type: "tub",
      tub_size: "66 qt",
      spawn_type: "rye grain",
      substrate_type: "CVG",
      bag_type: null,
      inoculated_on: "2026-08-09",
      colonized_on: null,
      fruiting_on: null,
      spent_on: null,
      contamination_flag: false,
      rating: null,
      issues: null,
      notes: null,
      lineage_parent_id: 1,
      created_at: "2026-08-09T15:00:00Z",
      strains: strainsGT,
      rooms: roomB,
    },
    {
      id: 2,
      lot_code: "SAPE-2607-B",
      stage: "colonization",
      strain_id: 2,
      room_id: 2,
      block_count: 2,
      substrate_weight_kg: 3.2,
      container_id: "TUB-08",
      container_type: "tub",
      tub_size: "32 qt",
      spawn_type: "rye grain",
      substrate_type: "CVG",
      bag_type: null,
      inoculated_on: "2026-07-28",
      colonized_on: null,
      fruiting_on: null,
      spent_on: null,
      contamination_flag: false,
      rating: null,
      issues: "Slow colonization on the north tub",
      // ~200-char stress note:
      notes:
        "Isolate is crawling — barely 40% at day 20, which matches the vendor's warning about this cross. Keeping it two degrees warmer than the GT tubs, re-checked the grain moisture, and split one jar to agar to verify the culture is clean before committing more substrate.",
      lineage_parent_id: null,
      created_at: "2026-07-28T15:00:00Z",
      strains: strainsSAPE,
      rooms: roomB,
    },
    {
      id: 3,
      lot_code: "JMF-2606-A",
      stage: "harvesting",
      strain_id: 3,
      room_id: 1,
      block_count: 3,
      substrate_weight_kg: 4.8,
      container_id: "TUB-05",
      container_type: "tub",
      tub_size: "54 qt",
      spawn_type: "oat grain",
      substrate_type: "CVG",
      bag_type: null,
      inoculated_on: "2026-06-12",
      colonized_on: "2026-06-27",
      fruiting_on: "2026-07-03",
      spent_on: null,
      contamination_flag: false,
      rating: 7,
      issues: null,
      notes: "F2 ratio dipped below floor — dried too slow in humid week.",
      lineage_parent_id: null,
      created_at: "2026-06-12T15:00:00Z",
      strains: strainsJMF,
      rooms: roomA,
    },
    {
      id: 4,
      lot_code: "LM-2605-A",
      stage: "fruiting",
      strain_id: 4,
      room_id: 1,
      block_count: 8,
      substrate_weight_kg: 8,
      container_id: "BAG-12",
      container_type: "bag",
      tub_size: null,
      spawn_type: "grain",
      substrate_type: "hardwood + bran",
      bag_type: "Unicorn 14A",
      inoculated_on: "2026-05-30",
      colonized_on: "2026-06-20",
      fruiting_on: "2026-08-01",
      spent_on: null,
      contamination_flag: false,
      rating: 9,
      issues: null,
      notes: null,
      lineage_parent_id: null,
      created_at: "2026-05-30T15:00:00Z",
      strains: strainsLM,
      rooms: roomA,
    },
    {
      id: 5,
      lot_code: "BO-2604-A",
      stage: "spent",
      strain_id: 5,
      room_id: null,
      block_count: 6,
      substrate_weight_kg: 8,
      container_id: "BAG-09",
      container_type: "bag",
      tub_size: null,
      spawn_type: "grain",
      substrate_type: "straw pellets",
      bag_type: "Unicorn 14A",
      inoculated_on: "2026-04-18",
      colonized_on: "2026-05-02",
      fruiting_on: "2026-05-09",
      spent_on: "2026-07-22",
      contamination_flag: false,
      rating: 6,
      issues: null,
      notes: "Spent blocks composted in the garden bed.",
      lineage_parent_id: null,
      created_at: "2026-04-18T15:00:00Z",
      strains: strainsBO,
      rooms: null,
    },
    {
      id: 7,
      lot_code: "JMF-2603-X",
      stage: "contaminated",
      strain_id: 3,
      room_id: null,
      block_count: 1,
      substrate_weight_kg: 1.6,
      container_id: "TUB-03",
      container_type: "tub",
      tub_size: "32 qt",
      spawn_type: "oat grain",
      substrate_type: "CVG",
      bag_type: null,
      inoculated_on: "2026-03-20",
      colonized_on: "2026-04-05",
      fruiting_on: null,
      spent_on: null,
      contamination_flag: true,
      rating: 1,
      issues: "Trichoderma at spawn-to-bulk",
      notes: "Culled day 3 of green mold. Grain jar from the same run also tossed.",
      lineage_parent_id: null,
      created_at: "2026-03-20T15:00:00Z",
      strains: strainsJMF,
      rooms: null,
    },
  ],

  // ── Harvests (base table) ───────────────────────────────────────────────
  harvests: [
    {
      id: 6,
      batch_id: 1,
      harvested_on: "2026-08-14",
      flush_number: 2,
      sku: "GT-DRY-0814",
      weight_kg: 1.96,
      dry_weight_kg: 0.21,
      dry_ratio_pct: 10.7,
      grade: "A",
      labor_minutes: 35,
      notes: null,
    },
    {
      id: 5,
      batch_id: 4,
      harvested_on: "2026-08-08",
      flush_number: 1,
      sku: "LM-FR-0808",
      weight_kg: 1.8,
      dry_weight_kg: 0.19,
      dry_ratio_pct: 10.6,
      grade: "A",
      labor_minutes: 25,
      notes: "Sold fresh at Saturday market",
    },
    {
      id: 4,
      batch_id: 3,
      harvested_on: "2026-07-30",
      flush_number: 2,
      sku: null,
      weight_kg: 1.15,
      dry_weight_kg: 0.09,
      dry_ratio_pct: 7.8,
      grade: "B",
      labor_minutes: 30,
      notes: "Dried slow during the humid week — ratio below floor",
    },
    {
      id: 3,
      batch_id: 1,
      harvested_on: "2026-07-25",
      flush_number: 1,
      sku: "GT-DRY-0725",
      weight_kg: 2.42,
      dry_weight_kg: 0.26,
      dry_ratio_pct: 10.7,
      grade: "A",
      labor_minutes: 40,
      notes: null,
    },
    {
      id: 2,
      batch_id: 5,
      harvested_on: "2026-07-18",
      flush_number: 3,
      sku: "BO-FR-0718",
      weight_kg: 3.3,
      dry_weight_kg: 0.31,
      dry_ratio_pct: 9.4,
      grade: "A",
      labor_minutes: 20,
      notes: null,
    },
    {
      id: 1,
      batch_id: 3,
      harvested_on: "2026-07-10",
      flush_number: 1,
      sku: "JMF-DRY-0710",
      weight_kg: 2.1,
      dry_weight_kg: 0.2,
      dry_ratio_pct: 9.5,
      grade: "A",
      labor_minutes: 45,
      notes: null,
    },
  ],

  // v_dry_ratio — newest first; first psychedelic row becomes the dashboard spotlight.
  v_dry_ratio: [
    {
      harvest_id: 6,
      batch_id: 1,
      lot_code: "GT-2608-A",
      harvested_on: "2026-08-14",
      flush_number: 2,
      strain_id: 1,
      strain: "Golden Teacher",
      fresh_g: 1960,
      dry_g: 210,
      dry_ratio_pct: 10.7,
      below_floor: false,
    },
    {
      harvest_id: 5,
      batch_id: 4,
      lot_code: "LM-2605-A",
      harvested_on: "2026-08-08",
      flush_number: 1,
      strain_id: 4,
      strain: "Lion's Mane",
      fresh_g: 1800,
      dry_g: 190,
      dry_ratio_pct: 10.6,
      below_floor: false,
    },
    {
      harvest_id: 4,
      batch_id: 3,
      lot_code: "JMF-2606-A",
      harvested_on: "2026-07-30",
      flush_number: 2,
      strain_id: 3,
      strain: "Jedi Mind Fuck",
      fresh_g: 1150,
      dry_g: 90,
      dry_ratio_pct: 7.8,
      below_floor: true,
    },
    {
      harvest_id: 3,
      batch_id: 1,
      lot_code: "GT-2608-A",
      harvested_on: "2026-07-25",
      flush_number: 1,
      strain_id: 1,
      strain: "Golden Teacher",
      fresh_g: 2420,
      dry_g: 260,
      dry_ratio_pct: 10.7,
      below_floor: false,
    },
    {
      harvest_id: 2,
      batch_id: 5,
      lot_code: "BO-2604-A",
      harvested_on: "2026-07-18",
      flush_number: 3,
      strain_id: 5,
      strain: "Blue Oyster",
      fresh_g: 3300,
      dry_g: 310,
      dry_ratio_pct: 9.4,
      below_floor: false,
    },
    {
      harvest_id: 1,
      batch_id: 3,
      lot_code: "JMF-2606-A",
      harvested_on: "2026-07-10",
      flush_number: 1,
      strain_id: 3,
      strain: "Jedi Mind Fuck",
      fresh_g: 2100,
      dry_g: 200,
      dry_ratio_pct: 9.5,
      below_floor: false,
    },
  ],

  v_yield_by_strain: [
    { strain_id: 1, strain: "Golden Teacher", batches: 2, fresh_kg: 4.38, biological_efficiency_pct: 67 },
    { strain_id: 5, strain: "Blue Oyster", batches: 1, fresh_kg: 3.3, biological_efficiency_pct: 41 },
    { strain_id: 3, strain: "Jedi Mind Fuck", batches: 2, fresh_kg: 3.25, biological_efficiency_pct: 34 },
    { strain_id: 4, strain: "Lion's Mane", batches: 1, fresh_kg: 1.8, biological_efficiency_pct: 23 },
    { strain_id: 2, strain: "Stargazer × Albino Penis Envy Isolate F4", batches: 1, fresh_kg: 0, biological_efficiency_pct: null },
    { strain_id: 6, strain: "Tidal Wave", batches: 0, fresh_kg: 0, biological_efficiency_pct: null },
  ],

  v_strain_scoreboard: [
    { id: 1, name: "Golden Teacher", ease_rating: 9, fresh_kg: 4.38, biological_efficiency_pct: 67, avg_dry_ratio: 10.7 },
    { id: 3, name: "Jedi Mind Fuck", ease_rating: 7, fresh_kg: 3.25, biological_efficiency_pct: 34, avg_dry_ratio: 8.9 },
    { id: 4, name: "Lion's Mane", ease_rating: 8, fresh_kg: 1.8, biological_efficiency_pct: 23, avg_dry_ratio: 10.6 },
    { id: 5, name: "Blue Oyster", ease_rating: 10, fresh_kg: 3.3, biological_efficiency_pct: 41, avg_dry_ratio: 9.4 },
    { id: 2, name: "Stargazer × Albino Penis Envy Isolate F4", ease_rating: 5, fresh_kg: 0, biological_efficiency_pct: null, avg_dry_ratio: null },
  ],

  // ── Dashboard weekly sparkline views ────────────────────────────────────
  v_harvest_weekly: [
    { week: "2026-06-29", fresh_g: 1450, dry_ratio_pct: 9.8 },
    { week: "2026-07-06", fresh_g: 2100, dry_ratio_pct: 9.5 },
    { week: "2026-07-13", fresh_g: 3300, dry_ratio_pct: 9.4 },
    { week: "2026-07-20", fresh_g: 2420, dry_ratio_pct: 10.7 },
    { week: "2026-07-27", fresh_g: 1150, dry_ratio_pct: 7.8 },
    { week: "2026-08-03", fresh_g: 1800, dry_ratio_pct: 10.6 },
    { week: "2026-08-10", fresh_g: 1960, dry_ratio_pct: 10.7 },
  ],
  v_active_batches_weekly: [
    { week: "2026-06-29", started: 1 },
    { week: "2026-07-06", started: 0 },
    { week: "2026-07-13", started: 0 },
    { week: "2026-07-20", started: 1 },
    { week: "2026-07-27", started: 1 },
    { week: "2026-08-03", started: 2 },
    { week: "2026-08-10", started: 1 },
  ],
  v_open_tasks_weekly: [
    { week: "2026-06-29", opened: 3 },
    { week: "2026-07-06", opened: 5 },
    { week: "2026-07-13", opened: 2 },
    { week: "2026-07-20", opened: 4 },
    { week: "2026-07-27", opened: 6 },
    { week: "2026-08-03", opened: 3 },
    { week: "2026-08-10", opened: 4 },
  ],

  // ── Dried inventory & valuation ─────────────────────────────────────────
  dry_inventory: [
    {
      id: 1,
      jar_id: "J-GT-0725-A",
      strain_id: 1,
      flush_number: 1,
      dry_weight_g: 260,
      used_g: 108,
      remaining_g: 152,
      location: "Cabinet B · shelf 2",
      notes: null,
      strains: { name: "Golden Teacher" },
    },
    {
      id: 2,
      jar_id: "J-GT-0814-B",
      strain_id: 1,
      flush_number: 2,
      dry_weight_g: 210,
      used_g: 0,
      remaining_g: 210,
      location: "Cabinet B · shelf 2",
      notes: "Curing with 62% Boveda",
      strains: { name: "Golden Teacher" },
    },
    {
      id: 3,
      jar_id: "J-JMF-0710-A",
      strain_id: 3,
      flush_number: 1,
      dry_weight_g: 200,
      used_g: 60,
      remaining_g: 140,
      location: "Cabinet B · shelf 1",
      notes: null,
      strains: { name: "Jedi Mind Fuck" },
    },
    {
      id: 4,
      jar_id: "J-LM-0808-A",
      strain_id: 4,
      flush_number: 1,
      dry_weight_g: 190,
      used_g: 20,
      remaining_g: 170,
      location: "Pantry",
      notes: "For tincture run",
      strains: { name: "Lion's Mane" },
    },
  ],

  v_inventory_valuation: [
    {
      jar_id: "J-GT-0725-A",
      strain: "Golden Teacher",
      remaining_g: 152,
      wholesale_low: 760,
      wholesale_high: 912,
      retail_low: 1216,
      retail_high: 1520,
      distributor_low: 532,
      distributor_high: 684,
    },
    {
      jar_id: "J-GT-0814-B",
      strain: "Golden Teacher",
      remaining_g: 210,
      wholesale_low: 1050,
      wholesale_high: 1260,
      retail_low: 1680,
      retail_high: 2100,
      distributor_low: 735,
      distributor_high: 945,
    },
    {
      jar_id: "J-JMF-0710-A",
      strain: "Jedi Mind Fuck",
      remaining_g: 140,
      wholesale_low: 700,
      wholesale_high: 840,
      retail_low: 1120,
      retail_high: 1400,
      distributor_low: 490,
      distributor_high: 630,
    },
  ],

  // ── Tasks & staff ───────────────────────────────────────────────────────
  staff: [
    { id: 1, name: "Isaac" },
    { id: 2, name: "Maya (weekends)" },
  ],

  tasks: [
    {
      id: 1,
      title: "Mist and fan Fruiting Tent A",
      description: "CO₂ trending high — extra FAE cycle after misting.",
      status: "in_progress",
      priority: "high",
      due_date: "2026-08-17",
      batch_id: 1,
      room_id: 1,
      assigned_to: 1,
      completion_action: "none",
      completion_stage: null,
      completion_room_id: null,
      batches: { id: 1, lot_code: "GT-2608-A" },
      rooms: { name: "Fruiting Tent A" },
      staff: { name: "Isaac" },
    },
    {
      id: 2,
      title: "Break and shake SAPE grain jars",
      description: "Only if agar check comes back clean.",
      status: "todo",
      priority: "medium",
      due_date: "2026-08-18",
      batch_id: 2,
      room_id: 2,
      assigned_to: 1,
      completion_action: "advance_stage",
      completion_stage: null,
      completion_room_id: null,
      batches: { id: 2, lot_code: "SAPE-2607-B" },
      rooms: { name: "Colonization Rack" },
      staff: { name: "Isaac" },
    },
    {
      id: 3,
      title: "Final flush pull on JMF-2606-A",
      description: null,
      status: "todo",
      priority: "high",
      due_date: "2026-08-15",
      batch_id: 3,
      room_id: 1,
      assigned_to: 2,
      completion_action: "set_stage",
      completion_stage: "spent",
      completion_room_id: null,
      batches: { id: 3, lot_code: "JMF-2606-A" },
      rooms: { name: "Fruiting Tent A" },
      staff: { name: "Maya (weekends)" },
    },
    {
      id: 4,
      title: "Move GT-2608-B tub to the fruiting tent",
      description: "Once fully colonized — check the corners.",
      status: "todo",
      priority: "medium",
      due_date: "2026-08-21",
      batch_id: 6,
      room_id: 2,
      assigned_to: null,
      completion_action: "move_room",
      completion_stage: null,
      completion_room_id: 1,
      batches: { id: 6, lot_code: "GT-2608-B" },
      rooms: { name: "Colonization Rack" },
      staff: null,
    },
    {
      id: 5,
      title: "Sterilize next round of grain bags",
      description: "12 bags, 90 min at 15 PSI.",
      status: "done",
      priority: "low",
      due_date: "2026-08-12",
      batch_id: null,
      room_id: 3,
      assigned_to: 1,
      completion_action: "none",
      completion_stage: null,
      completion_room_id: null,
      batches: null,
      rooms: { name: "Lab Closet" },
      staff: { name: "Isaac" },
    },
    {
      id: 6,
      title: "Reorder coco coir bricks",
      description: null,
      status: "done",
      priority: "medium",
      due_date: "2026-08-10",
      batch_id: null,
      room_id: null,
      assigned_to: 1,
      completion_action: "none",
      completion_stage: null,
      completion_room_id: null,
      batches: null,
      rooms: null,
      staff: { name: "Isaac" },
    },
  ],

  routines: [
    {
      id: 1,
      kind: "task",
      title: "Morning misting round",
      cadence: "daily",
      href: "/environment",
      notes: "All fruiting tents, before 9am",
      last_done_at: "2026-08-16T14:30:00Z",
      active: true,
      sort_order: 1,
      created_at: "2026-05-01T12:00:00Z",
    },
    {
      id: 2,
      kind: "task",
      title: "Fridge culture temp check",
      cadence: "daily",
      href: "/cultures",
      notes: "",
      last_done_at: "2026-08-15T15:00:00Z",
      active: true,
      sort_order: 2,
      created_at: "2026-05-01T12:00:00Z",
    },
    {
      id: 3,
      kind: "check_in",
      title: "Scan tubs for contamination",
      cadence: "daily",
      href: "/contamination",
      notes: "Especially SAPE-2607-B while it stalls",
      last_done_at: "2026-08-16T14:45:00Z",
      active: true,
      sort_order: 1,
      created_at: "2026-05-01T12:00:00Z",
    },
    {
      id: 4,
      kind: "automation",
      title: "Pull the Master sheet",
      cadence: "weekly",
      href: "/sync",
      notes: "Sheet → website, Monday mornings",
      last_done_at: "2026-08-15T13:05:00Z",
      active: true,
      sort_order: 1,
      created_at: "2026-05-01T12:00:00Z",
    },
    {
      id: 5,
      kind: "report",
      title: "Review yield by strain",
      cadence: "weekly",
      href: "/reports",
      notes: "Decide next inoculation mix",
      last_done_at: null,
      active: true,
      sort_order: 1,
      created_at: "2026-05-01T12:00:00Z",
    },
  ],

  // ── Supplies & equipment ────────────────────────────────────────────────
  inventory_items: [
    {
      id: 1,
      name: "Coco coir brick",
      category: "substrate",
      unit: "ea",
      quantity_on_hand: 4,
      reorder_threshold: 6,
      unit_cost: 3.5,
      supplier: "Out-Grow",
      location: "Garage shelf 1",
    },
    {
      id: 2,
      name: "Rye grain",
      category: "grain",
      unit: "lb",
      quantity_on_hand: 82,
      reorder_threshold: 25,
      unit_cost: 1.2,
      supplier: "Local feed store",
      location: "Garage bin A",
    },
    {
      id: 3,
      name: "Unicorn 14A grow bags",
      category: "packaging",
      unit: "ea",
      quantity_on_hand: 140,
      reorder_threshold: 50,
      unit_cost: 0.92,
      supplier: "Unicorn Bags",
      location: "Lab closet",
    },
    {
      id: 4,
      name: "Nitrile gloves (M)",
      category: "lab",
      unit: "box",
      quantity_on_hand: 7,
      reorder_threshold: 3,
      unit_cost: 9.5,
      supplier: "Out-Grow",
      location: "Lab closet",
    },
    {
      id: 5,
      name: "Isopropyl alcohol 70%",
      category: "lab",
      unit: "bottle",
      quantity_on_hand: 5,
      reorder_threshold: 2,
      unit_cost: 4.25,
      supplier: "Grocery",
      location: "Lab closet",
    },
    {
      id: 6,
      name: "Gypsum",
      category: "substrate",
      unit: "kg",
      quantity_on_hand: 9,
      reorder_threshold: 2,
      unit_cost: 2.1,
      supplier: "Out-Grow",
      location: "Garage shelf 1",
    },
  ],

  equipment: [
    {
      id: 1,
      name: "Laminar flow hood",
      spec_notes: "24\" FFU, HEPA H14 — filter replaced 2026-03",
      status: "active",
      room_id: 3,
      last_checked: "2026-08-01",
    },
    {
      id: 2,
      name: "AC Infinity 6\" inline fan",
      spec_notes: "Controller 69 Pro, ramped FAE schedule",
      status: "active",
      room_id: 1,
      last_checked: "2026-08-10",
    },
    {
      id: 3,
      name: "Ultrasonic humidifier",
      spec_notes: "Needs disc cleaning — output dropping",
      status: "maintenance",
      room_id: 1,
      last_checked: "2026-07-28",
    },
  ],

  // ── Cultures & spores ───────────────────────────────────────────────────
  culture_inventory: [
    {
      id: 1,
      label: "GT-LC-04",
      culture_type: "liquid_culture",
      strain_id: 1,
      status: "ready",
      quantity_on_hand: 3,
      unit: "jars",
      reorder_threshold: 1,
      location: "Fridge door",
      source: "In-house from agar",
      acquired_on: "2026-06-20",
      expires_on: "2026-12-20",
      notes: "Clean at 10 mL test inoc",
    },
    {
      id: 2,
      label: "SAPE-AG-11",
      culture_type: "agar_plate",
      strain_id: 2,
      status: "colonizing",
      quantity_on_hand: 4,
      unit: "plates",
      reorder_threshold: 0,
      location: "Lab closet incubator",
      source: "Isolate transfer",
      acquired_on: "2026-08-05",
      expires_on: null,
      notes: "Sector 2 looks rhizomorphic — keep",
    },
    {
      id: 3,
      label: "JMF-SS-02",
      culture_type: "spore_syringe",
      strain_id: 3,
      status: "stored",
      quantity_on_hand: 1,
      unit: "syringes",
      reorder_threshold: 2,
      location: "Fridge box 1",
      source: "Inoculate the World",
      acquired_on: "2026-03-02",
      expires_on: "2027-03-02",
      notes: "",
    },
    {
      id: 4,
      label: "LM-GS-07",
      culture_type: "grain_spawn",
      strain_id: 4,
      status: "ready",
      quantity_on_hand: 6,
      unit: "jars",
      reorder_threshold: 2,
      location: "Colonization rack",
      source: "In-house",
      acquired_on: "2026-07-25",
      expires_on: "2026-09-15",
      notes: "",
    },
    {
      id: 5,
      label: "TW-SP-01",
      culture_type: "spore_print",
      strain_id: 6,
      status: "ordered",
      quantity_on_hand: 1,
      unit: "prints",
      reorder_threshold: 0,
      location: "",
      source: "Sporeworks (crawler find)",
      acquired_on: null,
      expires_on: null,
      notes: "Ordered after the crawler flagged stock",
    },
    {
      id: 6,
      label: "GT-SL-01",
      culture_type: "slant",
      strain_id: 1,
      status: "stored",
      quantity_on_hand: 2,
      unit: "slants",
      reorder_threshold: 1,
      location: "Fridge box 2",
      source: "In-house backup",
      acquired_on: "2025-12-30",
      expires_on: "2026-06-30",
      notes: "Aging out — re-slant from LC this month",
    },
  ],

  // ── Presets (nested materials carry `count` so the batches page's
  //    preset_materials(count) aggregate read also works) ───────────────────
  recipes: [
    { id: 1, name: "CVG standard (coir/verm/gypsum)" },
    { id: 2, name: "Supplemented hardwood block" },
  ],

  batch_presets: [
    {
      id: 1,
      name: "Standard GT Monotub",
      strain_id: 1,
      recipe_id: 1,
      room_id: 2,
      container_type: "tub",
      tub_size: "66 qt",
      spawn_type: "rye grain",
      substrate_type: "CVG",
      bag_type: null,
      block_count: 4,
      substrate_weight_kg: 6.5,
      spawn_weight_kg: 1.4,
      notes: "The default cubensis run — one 66 qt tub, 1:4 spawn ratio.",
      active: true,
      strains: { name: "Golden Teacher" },
      recipes: { name: "CVG standard (coir/verm/gypsum)" },
      rooms: { name: "Colonization Rack" },
      preset_materials: [
        {
          id: 1,
          preset_id: 1,
          inventory_item_id: 1,
          name: "",
          quantity: 1,
          unit: "ea",
          inventory_items: { name: "Coco coir brick" },
          count: 3,
        },
        {
          id: 2,
          preset_id: 1,
          inventory_item_id: 6,
          name: "",
          quantity: 0.2,
          unit: "kg",
          inventory_items: { name: "Gypsum" },
          count: 3,
        },
        {
          id: 3,
          preset_id: 1,
          inventory_item_id: null,
          name: "Spring water",
          quantity: 4,
          unit: "L",
          inventory_items: null,
          count: 3,
        },
      ],
    },
    {
      id: 2,
      name: "Lion's Mane supplemented block",
      strain_id: 4,
      recipe_id: 2,
      room_id: 3,
      container_type: "bag",
      tub_size: null,
      spawn_type: "grain",
      substrate_type: "hardwood + bran",
      bag_type: "Unicorn 14A",
      block_count: 8,
      substrate_weight_kg: 2.5,
      spawn_weight_kg: 0.3,
      notes: null,
      active: true,
      strains: { name: "Lion's Mane" },
      recipes: { name: "Supplemented hardwood block" },
      rooms: { name: "Lab Closet" },
      preset_materials: [
        {
          id: 4,
          preset_id: 2,
          inventory_item_id: 3,
          name: "",
          quantity: 8,
          unit: "ea",
          inventory_items: { name: "Unicorn 14A grow bags" },
          count: 2,
        },
        {
          id: 5,
          preset_id: 2,
          inventory_item_id: null,
          name: "Hardwood pellets",
          quantity: 16,
          unit: "kg",
          inventory_items: null,
          count: 2,
        },
      ],
    },
  ],

  preset_materials: [
    { id: 1, preset_id: 1, inventory_item_id: 1, name: "", quantity: 1, unit: "ea", inventory_items: { name: "Coco coir brick" } },
    { id: 2, preset_id: 1, inventory_item_id: 6, name: "", quantity: 0.2, unit: "kg", inventory_items: { name: "Gypsum" } },
    { id: 3, preset_id: 1, inventory_item_id: null, name: "Spring water", quantity: 4, unit: "L", inventory_items: null },
    { id: 4, preset_id: 2, inventory_item_id: 3, name: "", quantity: 8, unit: "ea", inventory_items: { name: "Unicorn 14A grow bags" } },
    { id: 5, preset_id: 2, inventory_item_id: null, name: "Hardwood pellets", quantity: 16, unit: "kg", inventory_items: null },
  ],

  saved_batch_views: [
    { id: 1, name: "Fruiting now", filters: { stage: "fruiting" }, is_favorite: true, position: 1 },
    { id: 2, name: "Needs attention", filters: { attention: true }, is_favorite: true, position: 2 },
  ],

  // ── Reference / SOPs ────────────────────────────────────────────────────
  protocols: [
    {
      id: 1,
      name: "Agar to grain transfer",
      steps: [
        "Wipe down flow hood and still-air box with iso",
        "Flame scalpel until glowing, cool in agar corner",
        "Cut clean rhizomorphic wedge, avoid sectored zones",
        "Drop wedge into grain jar through injection port flap",
        "Label jar with strain, source plate and date",
      ],
    },
    {
      id: 2,
      name: "Bulk substrate pasteurization",
      steps: [
        "Hydrate coir brick with boiling water in cooler",
        "Add gypsum and vermiculite, mix thoroughly",
        "Hold 65–75°C for 90 minutes, lid closed",
        "Cool overnight to field capacity before spawning",
      ],
    },
    {
      id: 3,
      name: "Harvest & dry SOP",
      steps: [
        "Harvest before veil break where possible",
        "Weigh fresh per flush and log to the batch",
        "Fan-dry 4 h, then dehydrator at 52°C to cracker-dry",
        "Weigh dry, jar with desiccant and 62% pack",
        "Update dried-inventory jar record",
        "Flag lot if dry ratio lands below the floor",
      ],
    },
  ],

  reference_guides: [
    {
      id: 1,
      guide_type: "contamination",
      label: "Trichoderma (green mold)",
      appearance: "White mycelium turning forest green, spreads fast",
      cause: "Compromised sterile technique or dirty grain",
      action: "Cull immediately, bag the tub before moving it, bleach the shelf",
    },
    {
      id: 2,
      guide_type: "contamination",
      label: "Cobweb mold",
      appearance: "Wispy grey strands, faster and duller than mycelium",
      cause: "Stagnant humid air",
      action: "Spot-treat with 3% peroxide, increase FAE, monitor daily",
    },
    {
      id: 3,
      guide_type: "symptom",
      label: "Fuzzy feet on stems",
      appearance: "Cottony growth at stem base",
      cause: "High CO₂ / low fresh-air exchange",
      action: "Increase FAE cycles; check fan filter isn't clogged",
    },
    {
      id: 4,
      guide_type: "symptom",
      label: "Aborts / pins dying",
      appearance: "Black-capped pins that stop growing",
      cause: "Humidity swings or side pinning from light leaks",
      action: "Stabilize RH above 88%, block side light, harvest aborts promptly",
    },
  ],

  issue_log: [
    {
      id: 1,
      log_date: "2026-08-05",
      issue: "Green mold at spawn-to-bulk on JMF-2603-X",
      root_cause: "Grain jar had a hairline lid crack",
      resolution: "Culled lot; now inspecting every lid at pressure-cooker unload",
    },
    {
      id: 2,
      log_date: "2026-07-31",
      issue: "F2 dry ratio below floor on JMF-2606-A",
      root_cause: "Dehydrator overloaded during humid week",
      resolution: "Cap dryer at two flushes; run overnight cycle",
    },
    {
      id: 3,
      log_date: "2026-06-14",
      issue: "Blue Oyster fruiting stalled in garage heat",
      root_cause: "Ambient above 24°C for a week",
      resolution: "Retired BO for summer; re-run in October",
    },
  ],

  contamination_logs: [
    {
      id: 2,
      batch_id: 2,
      observed_on: "2026-08-12",
      contam_type: "cobweb",
      severity: "low",
      action_taken: "Peroxide spot-treat, doubled FAE",
      reported_by: "Isaac",
      batches: { lot_code: "SAPE-2607-B" },
    },
    {
      id: 1,
      batch_id: 7,
      observed_on: "2026-08-05",
      contam_type: "trichoderma",
      severity: "high",
      action_taken: "Culled and double-bagged; shelf bleached",
      reported_by: "Isaac",
      batches: { lot_code: "JMF-2603-X" },
    },
    {
      id: 3,
      batch_id: 5,
      observed_on: "2026-07-20",
      contam_type: "bacterial blotch",
      severity: "med",
      action_taken: "Trimmed affected cluster, sold the rest fresh same-day",
      reported_by: "Maya",
      batches: { lot_code: "BO-2604-A" },
    },
  ],

  // ── Batch detail extras ─────────────────────────────────────────────────
  batch_materials: [
    { id: 1, batch_id: 1, name: "Coco coir brick", quantity: 1, unit: "ea", inventory_item_id: 1 },
    { id: 2, batch_id: 1, name: "Gypsum", quantity: 0.2, unit: "kg", inventory_item_id: 6 },
    { id: 3, batch_id: 1, name: "Spring water", quantity: 4, unit: "L", inventory_item_id: null },
    { id: 4, batch_id: 1, name: "Rye grain spawn", quantity: 1.4, unit: "kg", inventory_item_id: 2 },
  ],

  batch_media: [
    {
      id: 1,
      batch_id: 1,
      storage_path: "batch-1/pins-day-3.jpg",
      original_filename: "pins-day-3.jpg",
      stage_snapshot: "fruiting",
      categories: ["pins", "progress"],
      captured_at: "2026-08-12T16:40:00Z",
      note: "Second-flush pins along the left canopy",
      is_cover: true,
    },
    {
      id: 2,
      batch_id: 1,
      storage_path: "batch-1/colonized-surface.jpg",
      original_filename: "colonized-surface.jpg",
      stage_snapshot: "colonization",
      categories: ["progress"],
      captured_at: "2026-07-15T18:05:00Z",
      note: "",
      is_cover: false,
    },
  ],

  batch_observations: [
    {
      id: 3,
      batch_id: 1,
      observed_at: "2026-08-15T15:20:00Z",
      stage_snapshot: "fruiting",
      kind: "voice",
      transcript:
        "Second flush is pinning heavier than the first — maybe forty pins across the left half alone. Surface still glistening after this morning's mist, no signs of blotch or cobweb anywhere, and the biggest cluster from flush one left a clean divot that's already re-knitting with fresh mycelium.",
      tags: ["pinning", "healthy_growth"],
    },
    {
      id: 2,
      batch_id: 1,
      observed_at: "2026-08-02T14:00:00Z",
      stage_snapshot: "fruiting",
      kind: "voice",
      transcript: "First flush canopy fully mature, harvesting tomorrow before veils break.",
      tags: ["harvest_ready"],
    },
    {
      id: 1,
      batch_id: 1,
      observed_at: "2026-07-14T13:30:00Z",
      stage_snapshot: "colonization",
      kind: "note",
      transcript: "Surface 90% colonized, corners lagging slightly. No mites, no smell.",
      tags: ["colonization_check"],
    },
  ],

  batch_change_events: [
    { id: 3, batch_id: 1, action: "Logged harvest F2 (1.96 kg fresh)", created_at: "2026-08-14T17:10:00Z", undone_at: null },
    { id: 2, batch_id: 1, action: "Advanced stage to fruiting", created_at: "2026-07-21T15:02:00Z", undone_at: null },
    { id: 1, batch_id: 1, action: "Set stage to harvesting", created_at: "2026-07-20T11:00:00Z", undone_at: "2026-07-20T11:04:00Z" },
  ],

  stage_events: [
    { id: 1, batch_id: 1, stage: "colonization", room_id: 2, note: "Inoculated 4 quarts into TUB-07", created_at: "2026-07-02T15:05:00Z" },
    { id: 2, batch_id: 1, stage: "fruiting", room_id: 1, note: "Advance stage", created_at: "2026-07-21T15:02:00Z" },
    { id: 3, batch_id: 4, stage: "moved", room_id: 1, note: "Moved to tent", created_at: "2026-08-01T16:00:00Z" },
  ],

  // ── Commerce ────────────────────────────────────────────────────────────
  customers: [
    {
      id: 5,
      name: "Cascadia Fungi Distribution",
      channel: "distributor",
      role: "Regional distributor",
      price_tier: "distributor",
      status: "integrated",
      follow_up_date: null,
      priority: 5,
      notes: "Standing monthly order; net-30 terms working fine.",
      contact_email: "orders@cascadiafungi.example.com",
      phone: "+1 541 555 0142",
      region: "OR / N. CA",
      volume_est: "10-15 lb/mo",
      address: "1200 Distribution Way, Eugene, OR",
      last_contact: "2026-08-11",
    },
    {
      id: 1,
      name: "Riverbend Wellness Collective",
      channel: "wholesale",
      role: "Buyer: Dana",
      price_tier: "wholesale",
      status: "active",
      follow_up_date: "2026-08-24",
      priority: 4,
      notes: "Loves the Lion's Mane tincture line. Wants a functional-box subscription for members.",
      contact_email: "dana@riverbendwellness.example.com",
      phone: "+1 458 555 0107",
      region: "Ashland",
      volume_est: "2-3 lb/mo",
      address: "88 Plaza Ave, Ashland, OR",
      last_contact: "2026-08-10",
    },
    {
      id: 4,
      // Deliberately long name to stress table/detail layout:
      name: "The Whole-Earth Cooperative Grocery & Wellness Collective of Greater Ashland",
      channel: "retail",
      role: "Category manager: Priya Raghunathan",
      price_tier: "retail",
      status: "warm",
      follow_up_date: "2026-08-20",
      priority: 3,
      notes: "Wants GAP audit trail before stocking fresh culinary line — send food-safety log export.",
      contact_email: "buying@wholeearthcoop.example.com",
      phone: "+1 541 555 0199",
      region: "Ashland",
      volume_est: "5 lb/wk fresh",
      address: "2450 Siskiyou Blvd, Ashland, OR",
      last_contact: "2026-08-06",
    },
    {
      id: 2,
      name: "Ashland Farmers Market",
      channel: "market",
      role: "Stall #14",
      price_tier: "retail",
      status: "active",
      follow_up_date: null,
      priority: 3,
      notes: "Saturday stall — fresh oyster and Lion's Mane sell out by 11am.",
      contact_email: "vendors@ashlandmarket.example.com",
      phone: null,
      region: "Ashland",
      volume_est: "4-6 lb/wk",
      address: null,
      last_contact: "2026-08-15",
    },
    {
      id: 3,
      name: "Sundrop Microdose Club",
      channel: "online",
      role: null,
      price_tier: "wholesale",
      status: "warm",
      follow_up_date: "2026-09-01",
      priority: 2,
      notes: "Waiting on their compliance review.",
      contact_email: "hello@sundrop.example.com",
      phone: null,
      region: "Remote",
      volume_est: "200 g/mo dried",
      address: null,
      last_contact: "2026-07-29",
    },
    {
      id: 6,
      name: "Moss & Mycelium Retail",
      channel: "retail",
      role: "Owner: Theo",
      price_tier: "retail",
      status: "cold",
      follow_up_date: null,
      priority: 1,
      notes: null,
      contact_email: null,
      phone: "+1 503 555 0123",
      region: "Portland",
      volume_est: null,
      address: "77 Alberta St, Portland, OR",
      last_contact: "2026-05-02",
    },
  ],

  // Orders newest first; nested customers + order_lines match every select.
  orders: [
    {
      id: 1,
      order_number: "ORD-2026-0012",
      customer_id: 1,
      channel: "wholesale",
      order_date: "2026-08-10",
      fulfillment_date: "2026-08-12",
      status: "complete",
      notes: null,
      financial_status: "paid",
      fulfillment_status: "fulfilled",
      customers: { id: 1, name: "Riverbend Wellness Collective" },
      order_lines: [
        { quantity: 2, unit_price: 84 },
        { quantity: 1, unit_price: 120 },
      ],
    },
    {
      id: 2,
      order_number: "ORD-2026-0011",
      customer_id: 2,
      channel: "market",
      order_date: "2026-08-02",
      fulfillment_date: "2026-08-02",
      status: "complete",
      notes: "Market pre-order, picked up at the stall",
      financial_status: "paid",
      fulfillment_status: "fulfilled",
      customers: { id: 2, name: "Ashland Farmers Market" },
      order_lines: [{ quantity: 4, unit_price: 18 }],
    },
    {
      id: 3,
      order_number: "ORD-2026-0010",
      customer_id: 3,
      channel: "online",
      order_date: "2026-07-28",
      fulfillment_date: null,
      status: "open",
      notes: "Hold until compliance review clears",
      financial_status: "pending",
      fulfillment_status: "unfulfilled",
      customers: { id: 3, name: "Sundrop Microdose Club" },
      order_lines: [{ quantity: 1, unit_price: 65 }],
    },
    {
      id: 4,
      order_number: "ORD-2026-0009",
      customer_id: 5,
      channel: "distributor",
      order_date: "2026-07-15",
      fulfillment_date: "2026-07-18",
      status: "complete",
      notes: null,
      financial_status: "paid",
      fulfillment_status: "fulfilled",
      customers: { id: 5, name: "Cascadia Fungi Distribution" },
      order_lines: [{ quantity: 3, unit_price: 84 }],
    },
    {
      id: 5,
      order_number: "ORD-2026-0008",
      customer_id: 4,
      channel: "retail",
      order_date: "2026-07-05",
      fulfillment_date: null,
      status: "cancelled",
      notes: "Cancelled pending GAP audit paperwork",
      financial_status: "refunded",
      fulfillment_status: "unfulfilled",
      customers: { id: 4, name: "The Whole-Earth Cooperative Grocery & Wellness Collective of Greater Ashland" },
      order_lines: [{ quantity: 5, unit_price: 12 }],
    },
  ],

  // Read directly by the batch detail page (downstream orders).
  order_lines: [
    {
      id: 1,
      order_id: 1,
      harvest_id: 3,
      quantity: 2,
      unit_price: 84,
      orders: {
        id: 1,
        order_number: "ORD-2026-0012",
        order_date: "2026-08-10",
        customers: { id: 1, name: "Riverbend Wellness Collective" },
      },
      products: { name: "Dried Golden Teacher · 1 oz" },
    },
    {
      id: 2,
      order_id: 2,
      harvest_id: 6,
      quantity: 4,
      unit_price: 18,
      orders: {
        id: 2,
        order_number: "ORD-2026-0011",
        order_date: "2026-08-02",
        customers: { id: 2, name: "Ashland Farmers Market" },
      },
      products: { name: "Lion's Mane fresh pint" },
    },
    {
      id: 3,
      order_id: 4,
      harvest_id: 1,
      quantity: 3,
      unit_price: 84,
      orders: {
        id: 4,
        order_number: "ORD-2026-0009",
        order_date: "2026-07-15",
        customers: { id: 5, name: "Cascadia Fungi Distribution" },
      },
      products: { name: "Dried Golden Teacher · 1 oz" },
    },
  ],

  subscriptions: [
    {
      id: 1,
      customer_id: 1,
      plan_name: "Monthly Functional Box",
      interval: "monthly",
      status: "active",
      started_on: "2026-05-01",
      next_renewal: "2026-09-01",
      price: 68,
      customers: { name: "Riverbend Wellness Collective" },
      subscription_items: [
        { quantity: 2, products: { name: "Lion's Mane extract tincture 2 oz" } },
        { quantity: 1, products: { name: "Lion's Mane fresh pint" } },
      ],
    },
    {
      id: 2,
      customer_id: 3,
      plan_name: "Microdose Club CSA",
      interval: "monthly",
      status: "active",
      started_on: "2026-06-15",
      next_renewal: "2026-09-15",
      price: 45,
      customers: { name: "Sundrop Microdose Club" },
      subscription_items: [{ quantity: 1, products: { name: "Dried Golden Teacher · 1 oz" } }],
    },
    {
      id: 3,
      customer_id: 2,
      plan_name: "Market stand standing order",
      interval: "weekly",
      status: "paused",
      started_on: "2026-04-04",
      next_renewal: null,
      price: 120,
      customers: { name: "Ashland Farmers Market" },
      subscription_items: [{ quantity: 6, products: { name: "Blue Oyster fresh lb" } }],
    },
  ],

  products: [
    {
      id: 1,
      name: "Dried Golden Teacher · 1 oz",
      sku: "GT-DRY-28",
      strain_id: 1,
      category: "dried",
      unit: "oz",
      status: "active",
      price: 84,
      distributor_price: 58,
      description: "Cracker-dry, jarred with 62% humidity pack.",
      inventory_quantity: 12,
      product_variants: [
        { title: "1 oz", price: 84, inventory_quantity: 12 },
        { title: "1/2 oz", price: 46, inventory_quantity: 20 },
      ],
    },
    {
      id: 2,
      name: "Lion's Mane fresh pint",
      sku: "LM-FR-PT",
      strain_id: 4,
      category: "fresh",
      unit: "pint",
      status: "active",
      price: 12,
      distributor_price: 8,
      description: "Harvested within 24 h of sale.",
      inventory_quantity: 18,
      product_variants: [{ title: "Pint", price: 12, inventory_quantity: 18 }],
    },
    {
      id: 3,
      name: "Lion's Mane extract tincture 2 oz",
      sku: "LM-TINC-2",
      strain_id: 4,
      category: "extract",
      unit: "bottle",
      status: "active",
      price: 32,
      distributor_price: 21,
      description: "Dual-extract, 1:4, fruiting body only.",
      inventory_quantity: 26,
      product_variants: [
        { title: "2 oz", price: 32, inventory_quantity: 26 },
        { title: "4 oz", price: 55, inventory_quantity: 9 },
      ],
    },
    {
      id: 4,
      name: "Blue Oyster fresh lb",
      sku: "BO-FR-LB",
      strain_id: 5,
      category: "fresh",
      unit: "lb",
      status: "draft",
      price: 14,
      distributor_price: 9,
      description: "Seasonal — returns in October.",
      inventory_quantity: 0,
      product_variants: null,
    },
  ],

  collections: [
    { id: 1, title: "Functional extracts" },
    { id: 2, title: "Fresh culinary" },
    { id: 3, title: "Microdose line" },
  ],

  price_tiers: [
    { id: 1, tier: "distributor", product_class: "dried", min_per_gram: 3.5, max_per_gram: 4.5, min_per_lb: null, max_per_lb: null },
    { id: 2, tier: "wholesale", product_class: "dried", min_per_gram: 5, max_per_gram: 6, min_per_lb: null, max_per_lb: null },
    { id: 3, tier: "retail", product_class: "dried", min_per_gram: 8, max_per_gram: 10, min_per_lb: null, max_per_lb: null },
    { id: 4, tier: "wholesale", product_class: "fresh gourmet", min_per_gram: null, max_per_gram: null, min_per_lb: 8, max_per_lb: 12 },
  ],

  v_commerce_kpis: [{ gross_sales: 1284, avg_order_value: 107, orders: 12 }],

  v_best_sellers: [
    { product_id: 1, name: "Dried Golden Teacher · 1 oz", units: 9, revenue: 756 },
    { product_id: 3, name: "Lion's Mane extract tincture 2 oz", units: 11, revenue: 352 },
    { product_id: 2, name: "Lion's Mane fresh pint", units: 14, revenue: 168 },
  ],

  v_customer_ltv: [
    { id: 5, name: "Cascadia Fungi Distribution", orders: 3, lifetime_value: 1260 },
    { id: 1, name: "Riverbend Wellness Collective", orders: 2, lifetime_value: 540 },
    { id: 2, name: "Ashland Farmers Market", orders: 1, lifetime_value: 72 },
  ],

  v_circular_economy: [{ spent_substrate_kg: 148.5, estimated_co2e_diverted_kg: 62.4 }],

  // ── Marketing ───────────────────────────────────────────────────────────
  discounts: [
    { id: 1, code: "MARKET10", discount_type: "percentage", value: 10, active: true },
    { id: 2, code: "WELCOME15", discount_type: "fixed", value: 15, active: true },
    { id: 3, code: "SPRING26", discount_type: "percentage", value: 20, active: false },
  ],

  gift_cards: [
    { id: 1, code: "GC-7F2K-91QD", balance: 25, status: "active" },
    { id: 2, code: "GC-3XN8-04TB", balance: 60.5, status: "active" },
  ],

  marketing_campaigns: [
    {
      id: 1,
      name: "August fresh drop",
      channel: "email",
      audience: "All subscribers",
      status: "sent",
      recipients: 214,
      opens: 131,
      clicks: 42,
      revenue: 386,
      sent_at: "2026-08-05T16:00:00Z",
    },
    {
      id: 2,
      name: "Lion's Mane tincture launch",
      channel: "email",
      audience: "Wellness segment",
      status: "sent",
      recipients: 96,
      opens: 61,
      clicks: 28,
      revenue: 512,
      sent_at: "2026-07-12T16:00:00Z",
    },
    {
      id: 3,
      name: "Market-stall loyalty punch card",
      channel: "in_person",
      audience: "Saturday market regulars",
      status: "draft",
      recipients: 0,
      opens: 0,
      clicks: 0,
      revenue: 0,
      sent_at: null,
    },
  ],

  abandoned_carts: [
    { id: 1, email: "fern.lover@example.com", subtotal: 84, recovered: false, created_at: "2026-08-14T21:12:00Z" },
    { id: 2, email: "chef.tomas@example.com", subtotal: 36, recovered: true, created_at: "2026-08-09T02:40:00Z" },
    { id: 3, email: null, subtotal: 129.5, recovered: false, created_at: "2026-08-01T19:03:00Z" },
  ],

  // ── Sourcing ────────────────────────────────────────────────────────────
  vendors: [
    { id: 1, name: "Sporeworks", category: "spores", products: "Cubensis spore syringes, prints", rating: 5, contact_priority: "primary", notes: "Fast shipping, clean syringes every time", url: "https://sporeworks.example.com" },
    {
      id: 2,
      // Deliberately long vendor name to stress layout:
      name: "Pacific Northwest Mycological Supply & Genetics Preservation Co-op",
      category: "spores",
      products: "Isolates, slants, rare crosses",
      rating: 4,
      contact_priority: "secondary",
      notes: "Member co-op — order window opens first Monday of the month only",
      url: "https://pnwmyco.example.org",
    },
    { id: 3, name: "North Spore", category: "functional", products: "Gourmet & functional spawn, plug spawn", rating: 5, contact_priority: "primary", notes: null, url: "https://northspore.example.com" },
    { id: 4, name: "Out-Grow", category: "supplies", products: "Substrate, bags, lab consumables", rating: 3, contact_priority: "primary", notes: "Cheap but slow — order two weeks ahead", url: "https://out-grow.example.com" },
    { id: 5, name: "Cascadia Wildcraft Collective", category: "sourcing", products: "Wild chanterelle, morel, lobster", rating: 4, contact_priority: "seasonal", notes: "Fall season only", url: null },
  ],

  purchase_orders: [
    {
      id: 1,
      vendor_id: 4,
      reference: "PO-2026-014",
      status: "ordered",
      ordered_at: "2026-08-11",
      expected_at: "2026-08-21",
      received_at: null,
      total: 218.4,
      notes: "Restock before the September inoculation push",
      vendors: { name: "Out-Grow" },
      purchase_order_items: [
        { id: 1, name: "Coco coir brick", quantity: 24, received_quantity: 0, unit_cost: 3.1 },
        { id: 2, name: "Unicorn 14A grow bags", quantity: 100, received_quantity: 0, unit_cost: 0.92 },
        { id: 3, name: "Nitrile gloves (M)", quantity: 6, received_quantity: 0, unit_cost: 8.75 },
      ],
    },
    {
      id: 2,
      vendor_id: 3,
      reference: "PO-2026-013",
      status: "received",
      ordered_at: "2026-07-22",
      expected_at: "2026-07-30",
      received_at: "2026-07-29",
      total: 146,
      notes: null,
      vendors: { name: "North Spore" },
      purchase_order_items: [
        { id: 4, name: "Lion's Mane grain spawn 5 lb", quantity: 4, received_quantity: 4, unit_cost: 29 },
        { id: 5, name: "Blue Oyster sawdust spawn", quantity: 2, received_quantity: 2, unit_cost: 15 },
      ],
    },
    {
      id: 3,
      vendor_id: 1,
      reference: "PO-2026-012",
      status: "received",
      ordered_at: "2026-07-02",
      expected_at: "2026-07-09",
      received_at: "2026-07-08",
      total: 54,
      notes: "JMF restock + TW print the crawler found",
      vendors: { name: "Sporeworks" },
      purchase_order_items: [
        { id: 6, name: "JMF spore syringe", quantity: 2, received_quantity: 2, unit_cost: 18 },
        { id: 7, name: "Tidal Wave spore print", quantity: 1, received_quantity: 1, unit_cost: 18 },
      ],
    },
  ],

  spore_source_listings: [
    {
      id: 1,
      strain_id: 6,
      vendor_name: "Sporeworks",
      source_url: "https://sporeworks.example.com/tidal-wave-spore-print",
      product_title: "Tidal Wave spore print",
      in_stock: true,
      price: "$18",
      found_at: "2026-08-10T07:00:00Z",
    },
    {
      id: 2,
      strain_id: 6,
      vendor_name: "Pacific Northwest Mycological Supply & Genetics Preservation Co-op",
      source_url: "https://pnwmyco.example.org/listings/tidal-wave-isolate-slant",
      product_title: "Tidal Wave isolate slant (member pre-order)",
      in_stock: false,
      price: "",
      found_at: "2026-08-03T07:00:00Z",
    },
    {
      id: 3,
      strain_id: 6,
      vendor_name: "Inoculate the World",
      source_url: "https://itw.example.com/tw-syringe",
      product_title: "Tidal Wave 10 mL spore syringe",
      in_stock: true,
      price: "$22",
      found_at: "2026-07-27T07:00:00Z",
    },
  ],

  // ── Safety & compliance ─────────────────────────────────────────────────
  food_safety_logs: [
    {
      id: 4,
      log_date: "2026-08-16",
      category: "sanitation",
      description: "Weekly deep clean: fruiting tent walls, humidifier reservoir, harvest knives",
      performed_by: "Isaac",
      passed: true,
      corrective_action: null,
    },
    {
      id: 3,
      log_date: "2026-08-14",
      category: "temperature",
      description: "Dehydrator calibration check against reference thermometer",
      performed_by: "Isaac",
      passed: true,
      corrective_action: null,
    },
    {
      id: 2,
      log_date: "2026-08-09",
      category: "pest",
      description: "Fungus gnats spotted near spent-block staging area",
      performed_by: "Maya",
      passed: false,
      corrective_action: "Moved spent blocks outside same day; added sticky traps at tent intake",
    },
    {
      id: 1,
      log_date: "2026-08-02",
      category: "hygiene",
      description: "Hand-wash station stocked; glove-change protocol reviewed with weekend help",
      performed_by: "Isaac",
      passed: true,
      corrective_action: null,
    },
  ],

  // ── Truth sources & sheet sync ──────────────────────────────────────────
  truth_sources: [
    {
      id: 1,
      label: "Master Cultivation Reference",
      url: "https://docs.google.com/spreadsheets/d/1AbCdEfGhIjKlMnOpQrStUvWxYz0123456789/edit",
      category: "cultivation",
      notes: "The workbook of record — strains, batches, harvests, buyers.",
      position: 1,
      height: 480,
      created_at: "2026-04-10T18:00:00Z",
    },
    {
      id: 2,
      label: "2026 Sales Tracker",
      url: "https://docs.google.com/spreadsheets/d/1ZyXwVuTsRqPoNmLkJiHgFeDcBa9876543210/edit",
      category: "sales",
      notes: null,
      position: 2,
      height: 420,
      created_at: "2026-06-02T18:00:00Z",
    },
  ],

  sheet_sync_queue: [
    {
      id: 41,
      entity: "batch",
      entity_id: 6,
      op: "insert",
      payload: { lot_code: "GT-2608-B", stage: "colonization" },
      synced_at: null,
      created_at: "2026-08-16T18:22:00Z",
      source: "web",
    },
    {
      id: 42,
      entity: "harvest",
      entity_id: 6,
      op: "insert",
      payload: { batch_id: 1, flush_number: 2, weight_kg: 1.96 },
      synced_at: null,
      created_at: "2026-08-14T17:12:00Z",
      source: "web",
    },
    {
      id: 40,
      entity: "customer",
      entity_id: 4,
      op: "update",
      payload: { status: "warm", follow_up_date: "2026-08-20" },
      synced_at: "2026-08-15T13:06:00Z",
      created_at: "2026-08-13T20:41:00Z",
      source: "web",
    },
    {
      id: 39,
      entity: "strain",
      entity_id: 2,
      op: "update",
      payload: { syringes_on_hand: 2 },
      synced_at: "2026-08-15T13:06:00Z",
      created_at: "2026-08-12T16:05:00Z",
      source: "web",
    },
  ],

  sheet_imports: [
    {
      id: 12,
      started_at: "2026-08-15T13:05:00Z",
      finished_at: "2026-08-15T13:06:10Z",
      source: "web button",
      status: "ok",
      rows_upserted: { strains: 6, batches: 7, harvests: 6, customers: 6, vendors: 5 },
      detail: "",
    },
    {
      id: 11,
      started_at: "2026-08-08T13:04:00Z",
      finished_at: "2026-08-08T13:05:20Z",
      source: "github action",
      status: "ok",
      rows_upserted: { strains: 6, batches: 6, harvests: 5, customers: 6 },
      detail: "",
    },
    {
      id: 10,
      started_at: "2026-08-01T13:04:00Z",
      finished_at: "2026-08-01T13:04:40Z",
      source: "github action",
      status: "error",
      rows_upserted: {},
      detail: "Sheet tab 'Buyers' missing header row",
    },
  ],

  // ── Feedback (read via /api/feedback for the layout's panel) ────────────
  feedback: [
    {
      id: 1,
      page: "/harvests",
      page_label: "Harvests",
      body: "Dry-ratio flag should link straight to the drying SOP.",
      status: "open",
      created_at: "2026-08-12T19:30:00Z",
    },
    {
      id: 2,
      page: "/batches",
      page_label: "Batches",
      body: "Board drag on mobile feels great now.",
      status: "done",
      created_at: "2026-08-05T22:10:00Z",
    },
  ],
};
